server:
  port: 8085

mybatis:
  typeAliasesPackage: com.blbd.volunteer.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志

spring:
  datasource:
    url: jdbc:mysql://8.140.242.177:3310/mgzm?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: mgzm_user
    password: mgzm123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      # 文件上传的最大值
      max-file-size: 512MB
      # 文件请求的最大值
      max-request-size: 512MB


#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 文件上传位置
fileLocation: static/files



